apiVersion: apps/v1
kind: Deployment
metadata:
  name: favorites-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favorites-service
  template:
    metadata:
      labels:
        app: favorites-service
    spec:
      containers:
        - name: favorites-service
          image: favorites-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
