apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-db
  template:
    metadata:
      labels:
        app: oracle-db
    spec:
      containers:
      - name: oracle
        image: gvenzl/oracle-xe:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 1521
        env:
        - name: ORACLE_PASSWORD
          value: system
        - name: ORACLE_USER
          value: "ssa"
        - name: ORACLE_SID
          value: "XE"
